# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.statBlockWidget_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.statBlockWidget_2.setObjectName("statBlockWidget_2")
        self.statBlockWidget = QtWidgets.QVBoxLayout(self.statBlockWidget_2)
        self.statBlockWidget.setObjectName("statBlockWidget")
        self.baseStatsWidget = QtWidgets.QFormLayout()
        self.baseStatsWidget.setObjectName("baseStatsWidget")
        self.nameLabel = QtWidgets.QLabel(parent=self.statBlockWidget_2)
        self.nameLabel.setObjectName("nameLabel")
        self.baseStatsWidget.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel
        )
        self.nameInput = QtWidgets.QLineEdit(parent=self.statBlockWidget_2)
        self.nameInput.setText("")
        self.nameInput.setMaxLength(128)
        self.nameInput.setFrame(True)
        self.nameInput.setPlaceholderText("")
        self.nameInput.setClearButtonEnabled(True)
        self.nameInput.setObjectName("nameInput")
        self.baseStatsWidget.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameInput
        )
        self.hpLabel = QtWidgets.QLabel(parent=self.statBlockWidget_2)
        self.hpLabel.setObjectName("hpLabel")
        self.baseStatsWidget.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.hpLabel
        )
        self.hpBox = QtWidgets.QSpinBox(parent=self.statBlockWidget_2)
        self.hpBox.setMinimum(1)
        self.hpBox.setMaximum(9999)
        self.hpBox.setObjectName("hpBox")
        self.baseStatsWidget.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.hpBox
        )
        self.acLabel = QtWidgets.QLabel(parent=self.statBlockWidget_2)
        self.acLabel.setObjectName("acLabel")
        self.baseStatsWidget.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.acLabel
        )
        self.acBox = QtWidgets.QSpinBox(parent=self.statBlockWidget_2)
        self.acBox.setMinimum(1)
        self.acBox.setMaximum(30)
        self.acBox.setProperty("value", 10)
        self.acBox.setObjectName("acBox")
        self.baseStatsWidget.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.acBox
        )
        self.speedLabel = QtWidgets.QLabel(parent=self.statBlockWidget_2)
        self.speedLabel.setObjectName("speedLabel")
        self.baseStatsWidget.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.speedLabel
        )
        self.speedBox = QtWidgets.QSpinBox(parent=self.statBlockWidget_2)
        self.speedBox.setMinimum(1)
        self.speedBox.setMaximum(999)
        self.speedBox.setProperty("value", 30)
        self.speedBox.setObjectName("speedBox")
        self.baseStatsWidget.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.speedBox
        )
        self.profLabel = QtWidgets.QLabel(parent=self.statBlockWidget_2)
        self.profLabel.setObjectName("profLabel")
        self.baseStatsWidget.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.profLabel
        )
        self.profBox = QtWidgets.QSpinBox(parent=self.statBlockWidget_2)
        self.profBox.setMaximum(20)
        self.profBox.setProperty("value", 2)
        self.profBox.setObjectName("profBox")
        self.baseStatsWidget.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.profBox
        )
        self.statBlockWidget.addLayout(self.baseStatsWidget)
        self.abilityScoresWidget = QtWidgets.QGroupBox(parent=self.statBlockWidget_2)
        self.abilityScoresWidget.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.abilityScoresWidget.setFlat(False)
        self.abilityScoresWidget.setCheckable(False)
        self.abilityScoresWidget.setChecked(False)
        self.abilityScoresWidget.setObjectName("abilityScoresWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.abilityScoresWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.intBox = QtWidgets.QSpinBox(parent=self.abilityScoresWidget)
        self.intBox.setMinimum(1)
        self.intBox.setMaximum(30)
        self.intBox.setProperty("value", 10)
        self.intBox.setObjectName("intBox")
        self.gridLayout.addWidget(self.intBox, 1, 1, 1, 1)
        self.dexBox = QtWidgets.QSpinBox(parent=self.abilityScoresWidget)
        self.dexBox.setMinimum(1)
        self.dexBox.setMaximum(30)
        self.dexBox.setProperty("value", 10)
        self.dexBox.setObjectName("dexBox")
        self.gridLayout.addWidget(self.dexBox, 0, 3, 1, 1)
        self.strBox = QtWidgets.QSpinBox(parent=self.abilityScoresWidget)
        self.strBox.setWrapping(False)
        self.strBox.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows
        )
        self.strBox.setMinimum(1)
        self.strBox.setMaximum(30)
        self.strBox.setProperty("value", 10)
        self.strBox.setObjectName("strBox")
        self.gridLayout.addWidget(self.strBox, 0, 1, 1, 1)
        self.intLabel = QtWidgets.QLabel(parent=self.abilityScoresWidget)
        self.intLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.intLabel.setObjectName("intLabel")
        self.gridLayout.addWidget(self.intLabel, 1, 0, 1, 1)
        self.wisLabel = QtWidgets.QLabel(parent=self.abilityScoresWidget)
        self.wisLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.wisLabel.setObjectName("wisLabel")
        self.gridLayout.addWidget(self.wisLabel, 1, 2, 1, 1)
        self.conBox = QtWidgets.QSpinBox(parent=self.abilityScoresWidget)
        self.conBox.setMinimum(1)
        self.conBox.setMaximum(30)
        self.conBox.setProperty("value", 10)
        self.conBox.setObjectName("conBox")
        self.gridLayout.addWidget(self.conBox, 0, 5, 1, 1)
        self.dexLabel = QtWidgets.QLabel(parent=self.abilityScoresWidget)
        self.dexLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.dexLabel.setObjectName("dexLabel")
        self.gridLayout.addWidget(self.dexLabel, 0, 2, 1, 1)
        self.wisBox = QtWidgets.QSpinBox(parent=self.abilityScoresWidget)
        self.wisBox.setSuffix("")
        self.wisBox.setMinimum(1)
        self.wisBox.setMaximum(30)
        self.wisBox.setProperty("value", 10)
        self.wisBox.setObjectName("wisBox")
        self.gridLayout.addWidget(self.wisBox, 1, 3, 1, 1)
        self.strLabel = QtWidgets.QLabel(parent=self.abilityScoresWidget)
        self.strLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.strLabel.setObjectName("strLabel")
        self.gridLayout.addWidget(self.strLabel, 0, 0, 1, 1)
        self.chaLabel = QtWidgets.QLabel(parent=self.abilityScoresWidget)
        self.chaLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.chaLabel.setObjectName("chaLabel")
        self.gridLayout.addWidget(self.chaLabel, 1, 4, 1, 1)
        self.chaBox = QtWidgets.QSpinBox(parent=self.abilityScoresWidget)
        self.chaBox.setMinimum(1)
        self.chaBox.setMaximum(30)
        self.chaBox.setProperty("value", 10)
        self.chaBox.setObjectName("chaBox")
        self.gridLayout.addWidget(self.chaBox, 1, 5, 1, 1)
        self.conLabel = QtWidgets.QLabel(parent=self.abilityScoresWidget)
        self.conLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.conLabel.setObjectName("conLabel")
        self.gridLayout.addWidget(self.conLabel, 0, 4, 1, 1)
        self.statBlockWidget.addWidget(self.abilityScoresWidget)
        self.attackLabel = QtWidgets.QLabel(parent=self.statBlockWidget_2)
        self.attackLabel.setObjectName("attackLabel")
        self.statBlockWidget.addWidget(self.attackLabel)
        self.attacksListView = QtWidgets.QListView(parent=self.statBlockWidget_2)
        self.attacksListView.setAlternatingRowColors(True)
        self.attacksListView.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.attacksListView.setObjectName("attacksListView")
        self.statBlockWidget.addWidget(self.attacksListView)
        self.attackButtonsLayout = QtWidgets.QGridLayout()
        self.attackButtonsLayout.setObjectName("attackButtonsLayout")
        self.addSaveAttackButton = QtWidgets.QPushButton(parent=self.statBlockWidget_2)
        self.addSaveAttackButton.setObjectName("addSaveAttackButton")
        self.attackButtonsLayout.addWidget(self.addSaveAttackButton, 0, 1, 1, 1)
        self.deleteAttackButton = QtWidgets.QPushButton(parent=self.statBlockWidget_2)
        self.deleteAttackButton.setEnabled(False)
        self.deleteAttackButton.setObjectName("deleteAttackButton")
        self.attackButtonsLayout.addWidget(self.deleteAttackButton, 1, 1, 1, 1)
        self.addRollAttackButton = QtWidgets.QPushButton(parent=self.statBlockWidget_2)
        self.addRollAttackButton.setAutoDefault(False)
        self.addRollAttackButton.setFlat(False)
        self.addRollAttackButton.setObjectName("addRollAttackButton")
        self.attackButtonsLayout.addWidget(self.addRollAttackButton, 0, 0, 1, 1)
        self.editAttackButton = QtWidgets.QPushButton(parent=self.statBlockWidget_2)
        self.editAttackButton.setEnabled(False)
        self.editAttackButton.setObjectName("editAttackButton")
        self.attackButtonsLayout.addWidget(self.editAttackButton, 1, 0, 1, 1)
        self.statBlockWidget.addLayout(self.attackButtonsLayout)
        self.multiattackLabel = QtWidgets.QLabel(parent=self.statBlockWidget_2)
        self.multiattackLabel.setObjectName("multiattackLabel")
        self.statBlockWidget.addWidget(self.multiattackLabel)
        self.multiattackListView = QtWidgets.QListView(parent=self.statBlockWidget_2)
        self.multiattackListView.setAlternatingRowColors(True)
        self.multiattackListView.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.multiattackListView.setObjectName("multiattackListView")
        self.statBlockWidget.addWidget(self.multiattackListView)
        self.multiattackButtonsLayout = QtWidgets.QHBoxLayout()
        self.multiattackButtonsLayout.setObjectName("multiattackButtonsLayout")
        self.addMultiattackButton = QtWidgets.QPushButton(parent=self.statBlockWidget_2)
        self.addMultiattackButton.setObjectName("addMultiattackButton")
        self.multiattackButtonsLayout.addWidget(self.addMultiattackButton)
        self.editMultiattackButton = QtWidgets.QPushButton(
            parent=self.statBlockWidget_2
        )
        self.editMultiattackButton.setEnabled(False)
        self.editMultiattackButton.setObjectName("editMultiattackButton")
        self.multiattackButtonsLayout.addWidget(self.editMultiattackButton)
        self.deleteMultiattackButton = QtWidgets.QPushButton(
            parent=self.statBlockWidget_2
        )
        self.deleteMultiattackButton.setEnabled(False)
        self.deleteMultiattackButton.setObjectName("deleteMultiattackButton")
        self.multiattackButtonsLayout.addWidget(self.deleteMultiattackButton)
        self.statBlockWidget.addLayout(self.multiattackButtonsLayout)
        self.horizontalLayout.addWidget(self.statBlockWidget_2)
        self.previewsWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.previewsWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.previewsWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.previewsWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.previewsWidget.setTabsClosable(False)
        self.previewsWidget.setTabBarAutoHide(False)
        self.previewsWidget.setObjectName("previewsWidget")
        self.srdPreviewWidget = QtWidgets.QWidget()
        self.srdPreviewWidget.setObjectName("srdPreviewWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.srdPreviewWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.srdPreviewPlot = MplCanvas(parent=self.srdPreviewWidget)
        self.srdPreviewPlot.setObjectName("srdPreviewPlot")
        self.horizontalLayout_3.addWidget(self.srdPreviewPlot)
        self.previewsWidget.addTab(self.srdPreviewWidget, "")
        self.mediumScaleCombatPreviewWidget = QtWidgets.QWidget()
        self.mediumScaleCombatPreviewWidget.setObjectName(
            "mediumScaleCombatPreviewWidget"
        )
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(
            self.mediumScaleCombatPreviewWidget
        )
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mediumScalePreviewPlot = MplCanvas(
            parent=self.mediumScaleCombatPreviewWidget
        )
        self.mediumScalePreviewPlot.setObjectName("mediumScalePreviewPlot")
        self.horizontalLayout_4.addWidget(self.mediumScalePreviewPlot)
        self.previewsWidget.addTab(self.mediumScaleCombatPreviewWidget, "")
        self.horizontalLayout.addWidget(self.previewsWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setSeparatorsCollapsible(False)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(parent=MainWindow)
        self.actionNew.setEnabled(True)
        self.actionNew.setIconVisibleInMenu(True)
        self.actionNew.setShortcutVisibleInContextMenu(True)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setEnabled(True)
        self.actionOpen.setIconVisibleInMenu(True)
        self.actionOpen.setShortcutVisibleInContextMenu(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setIconVisibleInMenu(True)
        self.actionSave.setShortcutVisibleInContextMenu(True)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(parent=MainWindow)
        self.actionSave_as.setIconVisibleInMenu(True)
        self.actionSave_as.setShortcutVisibleInContextMenu(True)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setMenuRole(QtGui.QAction.MenuRole.QuitRole)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setShortcutVisibleInContextMenu(True)
        self.actionExit.setObjectName("actionExit")
        self.actionExportDatasheet = QtGui.QAction(parent=MainWindow)
        self.actionExportDatasheet.setIconVisibleInMenu(True)
        self.actionExportDatasheet.setShortcutVisibleInContextMenu(True)
        self.actionExportDatasheet.setObjectName("actionExportDatasheet")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExportDatasheet)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.nameLabel.setBuddy(self.nameInput)
        self.hpLabel.setBuddy(self.hpBox)
        self.acLabel.setBuddy(self.acBox)
        self.speedLabel.setBuddy(self.speedBox)
        self.profLabel.setBuddy(self.profBox)
        self.intLabel.setBuddy(self.intBox)
        self.wisLabel.setBuddy(self.wisBox)
        self.dexLabel.setBuddy(self.dexBox)
        self.strLabel.setBuddy(self.strBox)
        self.chaLabel.setBuddy(self.chaBox)
        self.conLabel.setBuddy(self.conBox)

        self.retranslateUi(MainWindow)
        self.previewsWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.nameInput, self.hpBox)
        MainWindow.setTabOrder(self.hpBox, self.acBox)
        MainWindow.setTabOrder(self.acBox, self.speedBox)
        MainWindow.setTabOrder(self.speedBox, self.profBox)
        MainWindow.setTabOrder(self.profBox, self.strBox)
        MainWindow.setTabOrder(self.strBox, self.dexBox)
        MainWindow.setTabOrder(self.dexBox, self.conBox)
        MainWindow.setTabOrder(self.conBox, self.intBox)
        MainWindow.setTabOrder(self.intBox, self.wisBox)
        MainWindow.setTabOrder(self.wisBox, self.chaBox)
        MainWindow.setTabOrder(self.chaBox, self.attacksListView)
        MainWindow.setTabOrder(self.attacksListView, self.addRollAttackButton)
        MainWindow.setTabOrder(self.addRollAttackButton, self.addSaveAttackButton)
        MainWindow.setTabOrder(self.addSaveAttackButton, self.editAttackButton)
        MainWindow.setTabOrder(self.editAttackButton, self.deleteAttackButton)
        MainWindow.setTabOrder(self.deleteAttackButton, self.multiattackListView)
        MainWindow.setTabOrder(self.multiattackListView, self.addMultiattackButton)
        MainWindow.setTabOrder(self.addMultiattackButton, self.editMultiattackButton)
        MainWindow.setTabOrder(self.editMultiattackButton, self.deleteMultiattackButton)
        MainWindow.setTabOrder(self.deleteMultiattackButton, self.previewsWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "Medium Scale Combat for 5e Datasheet Generator")
        )
        self.statBlockWidget_2.setTitle(_translate("MainWindow", "Stat Block"))
        self.nameLabel.setText(_translate("MainWindow", "&Name"))
        self.hpLabel.setText(_translate("MainWindow", "Average &hit points"))
        self.acLabel.setText(_translate("MainWindow", "&Armor class"))
        self.speedLabel.setText(_translate("MainWindow", "&Speed"))
        self.speedBox.setSuffix(_translate("MainWindow", " ft."))
        self.profLabel.setText(_translate("MainWindow", "&Proficiency bonus"))
        self.profBox.setPrefix(_translate("MainWindow", "+"))
        self.abilityScoresWidget.setTitle(_translate("MainWindow", "Ability Scores"))
        self.intLabel.setText(_translate("MainWindow", "&Intelligence"))
        self.wisLabel.setText(_translate("MainWindow", "&Wisdom"))
        self.dexLabel.setText(_translate("MainWindow", "&Dexterity"))
        self.strLabel.setText(_translate("MainWindow", "S&trength"))
        self.chaLabel.setText(_translate("MainWindow", "&Charisma"))
        self.conLabel.setText(_translate("MainWindow", "C&onstitution"))
        self.attackLabel.setText(_translate("MainWindow", "Attacks"))
        self.addSaveAttackButton.setText(
            _translate("MainWindow", "Add an attack based on saving throw")
        )
        self.deleteAttackButton.setText(_translate("MainWindow", "Delete attack"))
        self.addRollAttackButton.setText(
            _translate("MainWindow", "Add an attack based on attack rolls")
        )
        self.editAttackButton.setText(_translate("MainWindow", "Edit attack"))
        self.multiattackLabel.setText(_translate("MainWindow", "Multiattacks"))
        self.addMultiattackButton.setText(_translate("MainWindow", "Add multiattack"))
        self.editMultiattackButton.setText(_translate("MainWindow", "Edit multiattack"))
        self.deleteMultiattackButton.setText(
            _translate("MainWindow", "Delete multiattack")
        )
        self.previewsWidget.setTabText(
            self.previewsWidget.indexOf(self.srdPreviewWidget),
            _translate("MainWindow", "5e Stat Block Preview"),
        )
        self.previewsWidget.setTabText(
            self.previewsWidget.indexOf(self.mediumScaleCombatPreviewWidget),
            _translate("MainWindow", "Medium Combat for 5e Stat Block Preview"),
        )
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExportDatasheet.setText(_translate("MainWindow", "Export datasheet"))
        self.actionExportDatasheet.setToolTip(
            _translate("MainWindow", "Export datasheet")
        )
        self.actionExportDatasheet.setShortcut(_translate("MainWindow", "Ctrl+E"))


from custom_ui.matplotlib import MplCanvas
